baseurl = "/"
languageCode = "en-us"
title = "Edgar Zamora"
theme = "hugo-theme-cleanwhite-master"
googleAnalytics = "UA-159054948-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[params]
  header_image = "https://images.unsplash.com/photo-1540745291638-2c71059043e5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80"

  
[permalinks]
    post = "/:year/:month/:day/:slug/"
  
[[params.addtional_menus]]
  title =  "Twitter"
  href = "https://twitter.com/Edgar_Zamora_"
  
[[params.addtional_menus]]
  title =  "GitHub"
  href = "https://github.com/Edgar-Zamora"
  
  
  
