---
title: Fixing a reveresed axis
author: Edgar Zamora
date: '2020-03-06'
slug: fixing-a-reveresed-axis
categories: []
tags:
  - ggplot
  - forecats
subtitle: ''
description: 'Here goes my descripition of the article.'
image: 'https://images.unsplash.com/photo-1509205477838-a534e43a849f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=498&q=80'
showtoc: false
draft: true
---


```{r load_packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(blogdown)
```


Data comes from week 13 of #TidyTuesday. 
```{r data}
seattle_pets <- read_csv(
  "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-26/seattle_pets.csv")

seattle_pets %>% 
  filter(!species %in% c("Goat", "Pig")) %>% 
  count(species, animals_name) %>% 
  group_by(species) %>% 
  top_n(10) %>% 
  mutate(animals_name = replace_na(animals_name, "Unkown")) %>% 
  ggplot(aes(animals_name, n)) + 
  geom_col() +
  labs(
    title = "Top 10 animal names among Cats and Dogs",
    y = "",
    x = "Name of Animal"
  ) +
  coord_flip() +
  facet_grid(~species) +
  theme(
    panel.background = element_blank(),
    panel.grid.major.x = element_line(colour = "grey70", size = .2),
    panel.grid.major.y = element_blank(),
    axis.ticks = element_blank()
  )


```
